# Transfer Learning MNIST

* Train a simple convnet on the MNIST dataset the first 5 digits [0..4].
* Freeze convolutional layers and fine-tune dense layers for the classification of digits [5..9].

## 1. Import necessary libraries for the model

In [1]:
#Importing important modules
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
import tensorflow as tf

Using TensorFlow backend.


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## 2. Import MNIST data and create 2 datasets with one dataset having digits from 0 to 4 and other from 5 to 9 

In [0]:
%matplotlib inline
# Load/Prep the Data
(x_train, y_train), (x_test, y_test) = mnist.load_data()
split_condition1 = y_train <5
split_condition2 = y_train >=5
# labels = y_train[[y_train[5]]
x_train_Ind04 = x_train [split_condition1]
x_test_Ind04 = x_test [y_test<5]
y_train_Ind04 = y_train[split_condition1]
y_test_Ind04 = y_test[y_test<5]

x_train_Ind59 = x_train [split_condition2]
x_test_Ind59 = x_test [y_test>=5]
y_train_Ind59 = y_train[split_condition2]
y_test_Ind59 = y_test[y_test>=5]
#mnist_df = mnist.load_data()
#split1, split2 = tf.split(value, num_or_size_splits=2, axis=1)
# df_1 = 
# df_2 = 
# x_train = x_train.reshape(x_train.shape[0], 28, 28, 1).astype('float32') #
# x_test = x_test.reshape(x_test.shape[0], 28, 28, 1).astype('float32')
# x_train /= 255 # normalization since we have max of 255
# x_test /= 255
# y_train = np_utils.to_categorical(y_train_num, 10) # since it is a classification problem we are explicitly mentioning this
# y_test = np_utils.to_categorical(y_test_num, 10)

# print('--- THE DATA ---')
# print('x_train shape:', x_train.shape)
# print(x_train.shape[0], 'train samples')
# print(x_test.shape[0], 'test samples')

In [4]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

## 3. Print x_train, y_train, x_test and y_test for both the datasets

In [5]:
print('x_train after 1st half splitting is:',x_train_Ind04)
print('y_train after 1st half splitting is:',y_train_Ind04)
print('x_train after 2nd half splitting is:',x_train_Ind59)
print('x_train after 2nd half splitting is:',y_train_Ind59)

print('x_test after 1st half splitting is:',x_test_Ind04)
print('y_test after 1st half splitting is:',y_test_Ind04)
print('x_test after 2nd half splitting is:',x_test_Ind59)
print('x_test after 2nd half splitting is:',y_test_Ind59)

('x_train after 1st half splitting is:', array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0,

## ** 4. Let us take only the dataset (x_train, y_train, x_test, y_test) for Integers 0 to 4 in MNIST **
## Reshape x_train and x_test to a 4 Dimensional array (channel = 1) to pass it into a Conv2D layer

In [6]:
print(x_train_Ind04.shape)
print(y_train_Ind04.shape)
print(x_test_Ind04.shape)
print(y_test_Ind04.shape)

(30596, 28, 28)
(30596,)
(5139, 28, 28)
(5139,)


In [7]:
import numpy as np
x_train_Ind04 = np.reshape(x_train_Ind04, (30596, 28, 28,1))
print(x_train_Ind04.shape)
x_test_Ind04 = np.reshape(x_test_Ind04, (5139, 28, 28,1))
print(x_test_Ind04.shape)

(30596, 28, 28, 1)
(5139, 28, 28, 1)


## 5. Normalize x_train and x_test by dividing it by 255

In [8]:
x_train_Ind04_Normalized = x_train_Ind04/255
print(x_train_Ind04_Normalized)
x_test_Ind04_Normalized = x_test_Ind04/255
print(x_test_Ind04_Normalized)

[[[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 ...


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]

## 6. Use One-hot encoding to divide y_train and y_test into required no of output classes

In [9]:
# convert class vectors to binary class matrices using one hot encoding
# y_train_Ind04_Onehot = keras.utils.to_categorical(y_train_Ind04)
# print(y_train_Ind04_Onehot)
# y_test_Ind04_Onehot = keras.utils.to_categorical(y_test_Ind04)
# print(y_test_Ind04_Onehot)

# We use get dummies because when to categorical is used for one hot encoding, it takes from 0 to 4 and 5 to 9 instead of all the way from 0 to 9  even after splitting into 2 halves.
# so we go for get dummies and not to categorical
import pandas as pd
y_train_Ind04_Onehot = pd.get_dummies(y_train_Ind04)
print(y_train_Ind04_Onehot)
y_test_Ind04_Onehot = pd.get_dummies(y_test_Ind04)
print(y_test_Ind04_Onehot)

       0  1  2  3  4
0      1  0  0  0  0
1      0  0  0  0  1
2      0  1  0  0  0
3      0  0  1  0  0
4      0  1  0  0  0
5      0  0  0  1  0
6      0  1  0  0  0
7      0  0  0  0  1
8      0  0  0  1  0
9      0  0  0  1  0
10     0  1  0  0  0
11     0  0  1  0  0
12     0  0  0  0  1
13     1  0  0  0  0
14     0  1  0  0  0
15     0  1  0  0  0
16     0  0  1  0  0
17     0  0  0  0  1
18     0  0  0  1  0
19     0  0  1  0  0
20     0  0  0  1  0
21     1  0  0  0  0
22     1  0  0  0  0
23     0  1  0  0  0
24     0  0  0  1  0
25     0  0  0  1  0
26     0  0  0  1  0
27     1  0  0  0  0
28     0  0  0  0  1
29     1  0  0  0  0
...   .. .. .. .. ..
30566  0  0  0  0  1
30567  1  0  0  0  0
30568  1  0  0  0  0
30569  0  0  0  0  1
30570  0  0  0  0  1
30571  1  0  0  0  0
30572  0  0  0  0  1
30573  1  0  0  0  0
30574  0  1  0  0  0
30575  0  0  0  1  0
30576  0  0  0  1  0
30577  0  1  0  0  0
30578  0  0  0  1  0
30579  0  0  0  1  0
30580  0  1  0  0  0
30581  0  0  

## 7. Build a sequential model with 2 Convolutional layers with 32 kernels of size (3,3) followed by a Max pooling layer of size (2,2) followed by a drop out layer to be trained for classification of digits 0-4  

In [0]:
from keras.datasets import cifar10, mnist
from keras.models import Sequential# sequential is one type of model; there are graph models as well
from keras.layers import Dense, Activation, Dropout, Flatten, Reshape # Dense is fully connected layer
from keras.layers import Convolution2D, MaxPooling2D #
from keras.utils import np_utils
import pickle # serialization fancy word for storing on disk
from matplotlib import pyplot as plt
import seaborn as sns
plt.rcParams['figure.figsize'] = (15, 8)

In [12]:
TRAIN = False
BATCH_SIZE = 32
EPOCHS = 10 

# Define the Type of Model
model2 = Sequential()
# 1st Conv Layer
model2.add(Convolution2D(32, 3, 3, input_shape=(28, 28,1)))
model2.add(Activation('relu'))

# 2nd Conv Layer
model2.add(Convolution2D(32, 3, 3))# input shape is known in the previous layer. so we don't give input shape
model2.add(Activation('relu'))

# Fully Connected Layer
model2.add(Flatten())
model2.add(Dense(128))
model2.add(Activation('relu'))


# Layer 1
model2.add(Dense(output_dim=5, bias=True))
model2.add(Activation("softmax"))

# Loss and Optimizer
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Store Training Results
early_stopping = keras.callbacks.EarlyStopping(monitor='val_acc', patience=5, verbose=1, mode='auto')
callback_list = [early_stopping]# [stats, early_stopping]

# Train the model
model2.fit(x_train_Ind04_Normalized, y_train_Ind04_Onehot, nb_epoch=EPOCHS, batch_size=BATCH_SIZE,
        validation_data=(x_test_Ind04_Normalized, y_test_Ind04_Onehot), callbacks=callback_list, verbose=True)

Instructions for updating:
Use tf.cast instead.


/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(28, 28, 1...)`
  
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:12: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3))`
  if sys.path[0] == '':
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:22: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=5, use_bias=True)`
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:34: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Train on 30596 samples, validate on 5139 samples
Epoch 1/10
30596/30596 [==============================] - 14s 467us/step - loss: 1.1196 - acc: 0.5316 - val_loss: 1.0692 - val_acc: 0.5544
Epoch 2/10
30596/30596 [==============================] - 9s 309us/step - loss: 1.0524 - acc: 0.5559 - val_loss: 1.0616 - val_acc: 0.5610
Epoch 3/10
30596/30596 [==============================] - 9s 310us/step - loss: 1.0283 - acc: 0.5638 - val_loss: 1.0447 - val_acc: 0.5666
Epoch 4/10
30596/30596 [==============================] - 9s 308us/step - loss: 1.0116 - acc: 0.5719 - val_loss: 1.0398 - val_acc: 0.5698
Epoch 5/10
30596/30596 [==============================] - 9s 310us/step - loss: 0.9961 - acc: 0.5760 - val_loss: 1.0530 - val_acc: 0.5593
Epoch 6/10
30596/30596 [==============================] - 9s 308us/step - loss: 0.9842 - acc: 0.5818 - val_loss: 1.0515 - val_acc: 0.5647
Epoch 7/10
30596/30596 [==============================] - 9s 308us/step - loss: 0.9746 - acc: 0.5849 - val_loss: 1.0594 - 

## 8. Post that flatten the data and add 2 Dense layers with 128 neurons and neurons = output classes with activation = 'relu' and 'softmax' respectively. Add dropout layer inbetween if necessary  

## 9. Print the training and test accuracy

In [17]:
model2.evaluate(x_train_Ind04, y_train_Ind04_Onehot)

30596/30596 [==============================] - 3s 91us/step


[0.541231201556238, 0.9662701006667538]

In [18]:
model2.evaluate(x_test_Ind04, y_test_Ind04_Onehot)

5139/5139 [==============================] - 0s 93us/step


[0.5016521055612138, 0.9686709477363753]

## 10. Make only the dense layers to be trainable and convolutional layers to be non-trainable

In [16]:
#Freezing layers in the model which don't have 'dense' in their name
for layer in model2.layers:
  if('dense' not in layer.name): #prefix detection to freeze layers which does not have dense
    #Freezing a layer
    layer.trainable = False # freezing the layer

#Module to print colourful statements
from termcolor import colored

#Check which layers have been frozen 
for layer in model2.layers:
  print (colored(layer.name, 'blue'))
  print (colored(layer.trainable, 'red'))

conv2d_3
False
activation_5
False
conv2d_4
False
activation_6
False
flatten_2
False
dense_3
True
activation_7
False
dense_4
True
activation_8
False


## 11. Use the model trained on 0 to 4 digit classification and train it on the dataset which has digits 5 to 9  (Using Transfer learning keeping only the dense layers to be trainable)

In [30]:
# repeat all the pre-processing steps for 5 to 9 like in 0 to 4 and then use the 0 to 4 model's learning via transfer learning to 5 to 9 data set
print(x_train_Ind59.shape)
print(y_train_Ind59.shape)
print(x_test_Ind59.shape)
print(y_test_Ind59.shape)

(29404, 28, 28)
(29404,)
(4861, 28, 28)
(4861,)


In [31]:
import numpy as np
x_train_Ind59 = np.reshape(x_train_Ind59,(x_train_Ind59.shape[0], 28, 28,1))
print(x_train_Ind59.shape)
x_test_Ind59 = np.reshape(x_test_Ind59,(x_test_Ind59.shape[0], 28, 28,1))
print(x_test_Ind59.shape)

(29404, 28, 28, 1)
(4861, 28, 28, 1)


In [32]:
# Normalizing the data
x_train_Ind59_Normalized = x_train_Ind59/255
print(x_train_Ind59_Normalized)
x_test_Ind59_Normalized = x_test_Ind59/255
print(x_test_Ind59_Normalized)

[[[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 ...


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]

In [33]:
# We use get dummies because when to categorical is used for one hot encoding, it takes from 0 to 4 and 5 to 9 instead of all the way from 0 to 9  even after splitting into 2 halves.
# so we go for get dummies and not to categorical
import pandas as pd
y_train_Ind59_Onehot = pd.get_dummies(y_train_Ind59)
print(y_train_Ind59_Onehot)
y_test_Ind59_Onehot = pd.get_dummies(y_test_Ind59)
print(y_test_Ind59_Onehot)

       5  6  7  8  9
0      1  0  0  0  0
1      0  0  0  0  1
2      1  0  0  0  0
3      0  1  0  0  0
4      0  0  1  0  0
5      0  0  0  1  0
6      0  1  0  0  0
7      0  0  0  0  1
8      0  0  0  0  1
9      0  0  1  0  0
10     0  0  0  1  0
11     0  1  0  0  0
12     0  0  0  0  1
13     1  0  0  0  0
14     0  1  0  0  0
15     0  0  1  0  0
16     0  1  0  0  0
17     0  0  0  1  0
18     0  0  1  0  0
19     0  0  0  0  1
20     0  0  0  0  1
21     0  0  0  1  0
22     1  0  0  0  0
23     0  0  0  0  1
24     0  0  1  0  0
25     0  0  0  0  1
26     0  0  0  1  0
27     0  0  0  0  1
28     0  1  0  0  0
29     1  0  0  0  0
...   .. .. .. .. ..
29374  0  0  0  1  0
29375  1  0  0  0  0
29376  0  0  0  0  1
29377  0  0  0  1  0
29378  0  0  0  1  0
29379  0  0  1  0  0
29380  1  0  0  0  0
29381  0  1  0  0  0
29382  1  0  0  0  0
29383  0  0  0  1  0
29384  0  0  1  0  0
29385  0  1  0  0  0
29386  0  0  0  1  0
29387  1  0  0  0  0
29388  0  0  0  0  1
29389  0  0  

In [34]:

# Train the model
model2.fit(x_train_Ind59_Normalized, y_train_Ind59_Onehot, nb_epoch=EPOCHS, batch_size=BATCH_SIZE,
        validation_data=(x_test_Ind59_Normalized, y_test_Ind59_Onehot), callbacks=callback_list, verbose=True)

Train on 29404 samples, validate on 4861 samples
Epoch 1/10
  480/29404 [..............................] - ETA: 11s - loss: 1.9384 - acc: 0.2521

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  
/usr/local/lib/python2.7/dist-packages/keras/engine/training.py:490: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'


29404/29404 [==============================] - 9s 310us/step - loss: 1.1509 - acc: 0.5195 - val_loss: 1.0555 - val_acc: 0.5542
Epoch 2/10
29404/29404 [==============================] - 9s 307us/step - loss: 1.0111 - acc: 0.5810 - val_loss: 1.0480 - val_acc: 0.5610
Epoch 3/10
29404/29404 [==============================] - 9s 307us/step - loss: 0.9766 - acc: 0.5947 - val_loss: 1.0364 - val_acc: 0.5668
Epoch 4/10
29404/29404 [==============================] - 9s 307us/step - loss: 0.9541 - acc: 0.6036 - val_loss: 1.0419 - val_acc: 0.5715
Epoch 5/10
29404/29404 [==============================] - 9s 306us/step - loss: 0.9361 - acc: 0.6101 - val_loss: 1.0404 - val_acc: 0.5735
Epoch 6/10
29404/29404 [==============================] - 9s 307us/step - loss: 0.9200 - acc: 0.6158 - val_loss: 1.0579 - val_acc: 0.5703
Epoch 7/10
29404/29404 [==============================] - 9s 308us/step - loss: 0.9060 - acc: 0.6212 - val_loss: 1.0751 - val_acc: 0.5666
Epoch 8/10
29404/29404 [=====================

## 12. Print the accuracy for classification of digits 5 to 9

In [35]:
model2.evaluate(x_train_Ind59, y_train_Ind59_Onehot)

29404/29404 [==============================] - 3s 91us/step


[1.6506695222583185, 0.8972928853136166]

In [36]:
model2.evaluate(x_test_Ind59, y_test_Ind59_Onehot)

4861/4861 [==============================] - 0s 93us/step


[1.6413236474627895, 0.8981691011429029]

## Sentiment analysis <br> 

The objective of the second problem is to perform Sentiment analysis from the tweets data collected from the users targeted at various mobile devices.
Based on the tweet posted by a user (text), we will classify if the sentiment of the user targeted at a particular mobile device is positive or not.

### 13. Read the dataset (tweets.csv) and drop the NA's while reading the dataset

In [37]:
from google.colab import drive
drive.mount ('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
import os
os.chdir('/content/drive/My Drive/Colab Notebooks')

In [0]:
tweets_df = pd.read_csv('tweets.csv').dropna()

### 14. Preprocess the text and add the preprocessed text in a column with name `text` in the dataframe.

In [0]:
def preprocess(text):
    try:
        return text.decode('ascii')
    except Exception as e:
        return ""

In [0]:
tweets_df['text'] = [preprocess(text) for text in tweets_df.tweet_text]

In [69]:
tweets_df.head(5)

tweet_text  \
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...   
1  @jessedee Know about @fludapp ? Awesome iPad/i...   
2  @swonderlin Can not wait for #iPad 2 also. The...   
3  @sxsw I hope this year's festival isn't as cra...   
4  @sxtxstate great stuff on Fri #SXSW: Marissa M...   

  emotion_in_tweet_is_directed_at  \
0                          iPhone   
1              iPad or iPhone App   
2                            iPad   
3              iPad or iPhone App   
4                          Google   

  is_there_an_emotion_directed_at_a_brand_or_product  \
0                                   Negative emotion   
1                                   Positive emotion   
2                                   Positive emotion   
3                                   Negative emotion   
4                                   Positive emotion   

                                                text  
0  .@wesley83 I have a 3G iPhone. After 3 hrs twe...  
1  @jessedee Know about @fludapp ? Awesome iPad/i...  
2  @swonderlin Can not wait for #iPad 2 also. The...  
3  @sxsw I hope this year's festival isn't as cra...  
4  @sxtxstate great stuff on Fri #SXSW: Marissa M...

### 15. Consider only rows having Positive emotion and Negative emotion and remove other rows from the dataframe.

In [0]:
tweets_df = tweets_df[(tweets_df.is_there_an_emotion_directed_at_a_brand_or_product == 'Negative emotion') | (tweets_df.is_there_an_emotion_directed_at_a_brand_or_product =='Positive emotion')]

### 16. Represent text as numerical data using `CountVectorizer` and get the document term frequency matrix

#### Use `vect` as the variable name for initialising CountVectorizer.

In [0]:
# use CountVectorizer to create document-term matrices from X_train and X_test
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
tweets_df_dtm = vect.fit_transform(tweets_df['text'])


### 17. Find number of different words in vocabulary

In [72]:
dir(vect)

['__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__getstate__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_limit_features',
 '_sort_features',
 '_stop_words_id',
 '_validate_params',
 '_validate_vocabulary',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'stop_words_',
 'strip_accents',
 't

#### Tip: To see all available functions for an Object use dir

In [73]:
print(len(vect.get_feature_names()))

5482


### 18. Find out how many Positive and Negative emotions are there.

Hint: Use value_counts on that column

In [74]:
tweets_df['is_there_an_emotion_directed_at_a_brand_or_product'].value_counts()

Positive emotion    2672
Negative emotion     519
Name: is_there_an_emotion_directed_at_a_brand_or_product, dtype: int64

### 19. Change the labels for Positive and Negative emotions as 1 and 0 respectively and store in a different column in the same dataframe named 'Label'

Hint: use map on that column and give labels

In [0]:
tweets_df['Label'] = tweets_df['is_there_an_emotion_directed_at_a_brand_or_product'].map({'Positive emotion':1,'Negative emotion':0})

### 20. Define the feature set (independent variable or X) to be `text` column and `labels` as target (or dependent variable)  and divide into train and test datasets

In [0]:
X = tweets_df['text']
y = tweets_df['Label']

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


## 21. **Predicting the sentiment:**


### Use Naive Bayes and Logistic Regression and their accuracy scores for predicting the sentiment of the given text

In [0]:
#tweets_df['Label']

In [90]:
# use default options for CountVectorizer
#vect = CountVectorizer()
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
vect = CountVectorizer(ngram_range=(1,2))

# create document-term matrices
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)

# use Naive Bayes to predict the star rating
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)

# calculate accuracy
print (accuracy_score(y_test, y_pred_class))

0.8748043818466353


In [0]:
# import and instantiate a logistic regression model
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [94]:
# train the model using X_train_dtm
logreg.fit(X_train_dtm, y_train)

/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
# make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test_dtm)

In [96]:
# calculate predicted probabilities for X_test_dtm
y_pred_prob = logreg.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([0.96635096, 0.94900332, 0.99466192, 0.8342472 , 0.8478717 ,
       0.95781765, 0.99784265, 0.98368943, 0.97299314, 0.93547715,
       0.98742885, 0.72335086, 0.97874119, 0.96398002, 0.98315055,
       0.95221503, 0.88628961, 0.99376448, 0.06183564, 0.98516375,
       0.97159072, 0.91527306, 0.98802102, 0.99343684, 0.96172606,
       0.8478717 , 0.98198695, 0.95804287, 0.95182612, 0.9179835 ,
       0.99611237, 0.99412396, 0.78378835, 0.8478717 , 0.86316186,
       0.54977833, 0.81865456, 0.98894488, 0.95300733, 0.93956819,
       0.99313416, 0.95051353, 0.66898249, 0.97983331, 0.98469979,
       0.9883219 , 0.97447512, 0.98463811, 0.9898438 , 0.93660198,
       0.96895819, 0.99571629, 0.90612694, 0.98422309, 0.9637837 ,
       0.99115833, 0.94838627, 0.98973383, 0.99351141, 0.88805914,
       0.97192283, 0.98083342, 0.91941782, 0.99757644, 0.99181968,
       0.96535638, 0.98617801, 0.95105563, 0.97204811, 0.96472183,
       0.97444635, 0.98201112, 0.98289906, 0.98939796, 0.96831

In [98]:
# calculate accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)
# calculate accuracy
metrics.accuracy_score(y_test, y_pred_class)

0.8763693270735524

## 22. Create a function called `tokenize_predict` which can take count vectorizer object as input and prints the accuracy for x (text) and y (labels)

In [0]:
def tokenize_predict(vect):
    x_train_dtm = vect.fit_transform(x_train)
    print('Features: ', x_train_dtm.shape[1])
    x_test_dtm = vect.transform(x_test)
    nb = MultinomialNB()
    nb.fit(x_train_dtm, y_train)
    y_pred_class = nb.predict(x_test_dtm)
    print('Accuracy: ', metrics.accuracy_score(y_test, y_pred_class))

### Create a count vectorizer function which includes n_grams = 1,2  and pass it to tokenize_predict function to print the accuracy score

### Create a count vectorizer function with stopwords = 'english'  and pass it to tokenize_predict function to print the accuracy score

In [100]:
# use default options for CountVectorizer
#vect = CountVectorizer()
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
vect = CountVectorizer(ngram_range=(1,2),stop_words='english')

# create document-term matrices
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)

# use Naive Bayes to predict the star rating
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)

# calculate accuracy
print (accuracy_score(y_test, y_pred_class))

0.8685446009389671


### Create a count vectorizer function with stopwords = 'english' and max_features =300  and pass it to tokenize_predict function to print the accuracy score

In [101]:
# use default options for CountVectorizer
#vect = CountVectorizer()
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
vect = CountVectorizer(ngram_range=(1,2),stop_words='english',max_features=300)

# create document-term matrices
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)

# use Naive Bayes to predict the star rating
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)

# calculate accuracy
print (accuracy_score(y_test, y_pred_class))

0.8028169014084507


### Create a count vectorizer function with n_grams = 1,2  and max_features = 15000  and pass it to tokenize_predict function to print the accuracy score

In [102]:
# use default options for CountVectorizer
#vect = CountVectorizer()
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
vect = CountVectorizer(ngram_range=(1,2),stop_words='english',max_features=15000)

# create document-term matrices
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)

# use Naive Bayes to predict the star rating
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)

# calculate accuracy
print (accuracy_score(y_test, y_pred_class))

0.8685446009389671


### Create a count vectorizer function with n_grams = 1,2  and include terms that appear at least 2 times (min_df = 2)  and pass it to tokenize_predict function to print the accuracy score

In [103]:
# use default options for CountVectorizer
#vect = CountVectorizer()
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
vect = CountVectorizer(ngram_range=(1,2),min_df=2)

# create document-term matrices
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)

# use Naive Bayes to predict the star rating
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)

# calculate accuracy
print (accuracy_score(y_test, y_pred_class))

0.8591549295774648
