In [1]:
#downgrading the version of numpy

!pip install numpy==1.16.2
import numpy as np
print(np.__version__)

1.16.2


In [0]:
from keras.datasets import imdb

In [0]:
vocab_size = 10000

In [0]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)

In [0]:
from keras.preprocessing.sequence import pad_sequences
vocab_size = 10000 #vocab size
maxlen = 300

In [0]:
#load dataset as a list of ints
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)
#make all sequences of the same length
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test =  pad_sequences(x_test, maxlen=maxlen)
#y_train = pad_sequences(y_train, maxlen=maxlen)

In [23]:
x_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [57]:
#Creating the word index

word_to_index = imdb.get_word_index()
for (k,v) in word_to_index.items():
  word_to_index[k] = v + 3

index_to_word = {}
index_to_word[0] = "PAD"
index_to_word[1] = "START"
index_to_word[2] = "OOV"
for (k,v) in word_to_index.items():
  index_to_word[v] = k
for r in range(len(x_train)):
  for c in range(len(x_train[r])):
    idx=x_train[r][c]
    wrd=index_to_word[idx]
    print(wrd)
  print(" -> %d" % y_train[r])
print("\n")

know
off
ends
and
characters
poorly
says
doesn't
cool
most
turn
at
completely
behind
girl
taken
means
what
kill
wasn't
pretty
etc
close
tells
wait
clearly
word
musical
next
its
make
supposed
later
meets
attention
looked
being
star
got
care
local
works
most
brilliant
fight
create
main
annoying
known
career
main
sets
around
self
two
around
nature
i'd
fi
given
fact
real
general
video
much
ago
who
america
like
casting
battle
horrible
including
anyway
whatever
group
two
8
joe
comedy
case
talking
entire
perfect
people
bad
peter
has
writing
sounds
zombie
somehow
different
whether
business
believable
reviews
turned
paul
4
 -> 0
some
we
important
was
here
school
okay
help
place
lines
shown
four
mean
appears
exactly
anything
everything
saw
moving
took
realize
there's
about
truth
overall
film's
point
having
said
beautiful
earth
totally
watch
british
modern
society
american
involved
now
took
serious
gets
matter
fantasy
say
war
older
making
getting
leads
taking
liked
storyline
poorly
lot
story
evil

KeyError: ignored

In [0]:
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential, load_model
from keras.layers import LSTM, Dense, Dropout, Embedding, Masking, Bidirectional
from keras.optimizers import Adam
from keras import backend
from keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau


In [0]:
model = Sequential()

In [0]:
# Embedding layer
model.add(
    Embedding(
        input_dim=1000,
        output_dim=100,
        weights=None,
        trainable=True))

In [27]:
# Recurrent layer
model.add(
    LSTM(
        64, return_sequences=False, dropout=0.1,
        recurrent_dropout=0.1))

# Fully connected layer
model.add(Dense(64, activation='sigmoid'))

# Dropout for regularization
model.add(Dropout(0.5))

# Output layer
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(
    optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 100)         100000    
_________________________________________________________________
lstm_2 (LSTM)                (None, 64)                42240     
_________________________________________________________________
dense_3 (Dense)              (None, 64)                4160      
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 65        
Total params: 146,465
Trainable params: 146,465
Non-trainable params: 0
_________________________________________________________________


In [0]:
callback_reduce_lr = ReduceLROnPlateau(monitor='acc',
                                      factor=0.1,
                                      min_lr=1e-4,
                                      patience=0,
                                      verbose=2)

In [0]:
SEQUENCES = 50
TIME_STEPS = 100

In [0]:
import numpy as np

In [0]:
x_train = np.random.randint(1000, size=(SEQUENCES, TIME_STEPS), dtype='int32')


In [32]:
x_train

array([[  3, 243, 983, 952, 849, 815, 609, 766, 116, 983, 389, 144, 365,
        135, 873,  40, 981, 560, 248,  59, 485, 866, 397,  19,  84, 242,
         48, 860,  34, 902, 607, 511,  84, 701, 279, 373, 973, 327, 281,
        852, 184, 666, 157, 393, 137, 749, 435, 756,   4, 317, 998,  23,
        514, 195, 501, 920, 907, 449, 370, 463, 357, 747, 114, 363, 805,
         37, 127, 512, 237, 275, 674, 339, 400, 363, 553, 852,  22,   8,
         84, 372, 283, 360, 188, 469, 796, 663, 777, 449, 689, 932, 245,
        316,  99, 236, 796, 706,  49, 626, 489, 657],
       [947, 142, 202,  24, 880, 454, 499, 145, 501, 580, 641, 579, 372,
        408, 757, 214, 865,  21, 626, 117, 634, 886, 154, 373, 433, 681,
        630, 626, 724,  85, 886,  15, 610, 864, 900, 905, 531, 624, 455,
        430,  50,  42, 433, 413, 584, 305, 263, 114, 322, 988, 216, 871,
        175, 119,  31, 599, 801, 319, 738, 338, 179,  33, 366, 356, 632,
        877, 461, 259, 541,  82, 392, 257, 481, 233, 541, 220, 868,  3

In [0]:
y_train = np.random.rand(SEQUENCES)


In [34]:
y_train

array([0.24001922, 0.9104469 , 0.64828027, 0.47211242, 0.52354797])

In [44]:
intialmodel = model.fit(x_train, y_train, epochs = 500, batch_size = 50,verbose=1,callbacks=[callback_reduce_lr]) 


Epoch 1/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6379 - acc: 0.0000e+00
Epoch 2/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6918 - acc: 0.0000e+00
Epoch 3/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6538 - acc: 0.0000e+00
Epoch 4/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6661 - acc: 0.0000e+00
Epoch 5/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6651 - acc: 0.0000e+00
Epoch 6/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6745 - acc: 0.0000e+00
Epoch 7/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6865 - acc: 0.0000e+00
Epoch 8/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6479 - acc: 0.0000e+00
Epoch 9/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6615 - acc: 0.0000e+00
Epoch 10/500
50/50 [==============================] - 0s 3ms/step - loss: 0.6476 - acc: 0.0000e+00
Epoch 11/500
50/50 

In [45]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:
#Save the model
model.save('/content/drive/My Drive/Residency 9/Project/SequenceModelsNLP/NLPModel.h5')

In [0]:
model = load_model('/content/drive/My Drive/Residency 9/Project/SequenceModelsNLP/NLPModel.h5')

In [48]:
model.fit(x_train, y_train, batch_size=50, epochs=500)

Epoch 1/500
50/50 [==============================] - 1s 15ms/step - loss: 0.5792 - acc: 0.0000e+00
Epoch 2/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5946 - acc: 0.0000e+00
Epoch 3/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5957 - acc: 0.0000e+00
Epoch 4/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5828 - acc: 0.0000e+00
Epoch 5/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5876 - acc: 0.0000e+00
Epoch 6/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5894 - acc: 0.0000e+00
Epoch 7/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5912 - acc: 0.0000e+00
Epoch 8/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5956 - acc: 0.0000e+00
Epoch 9/500
50/50 [==============================] - 0s 4ms/step - loss: 0.5931 - acc: 0.0000e+00
Epoch 10/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5956 - acc: 0.0000e+00
Epoch 11/500
50/50

In [51]:
print(model.evaluate(x_train, y_train, batch_size = 50))
print('\nModel Performance: Log Loss and Accuracy on validation data')
print(model.evaluate(x_test, y_test, batch_size = 50))

50/50 [==============================] - 0s 726us/step
[0.5455308556556702, 0.0]

Model Performance: Log Loss and Accuracy on validation data
25000/25000 [==============================] - 54s 2ms/step
[1.056697980761528, 0.4983199992775917]
